/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unpatched_Main */

#ifndef _Included_unpatched_Main
#define _Included_unpatched_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unpatched_Main
 * Method:    loadLibUnpatched
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_unpatched_Main_loadLibUnpatched
  (JNIEnv *, jclass);

/*
 * Class:     unpatched_Main
 * Method:    execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_unpatched_Main_execute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
