/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thread_Main */

#ifndef _Included_thread_Main
#define _Included_thread_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thread_Main
 * Method:    startBusyThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thread_Main_startBusyThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
