/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

extern "C" JNIEXPORT void JNICALL Java_beginend_BeginEnd_start0(JNIEnv* env, jclass cls) {
}

extern "C" JNIEXPORT void JNICALL Java_beginend_BeginEnd_start1(JNIEnv* env, jclass cls) {
}


extern "C" JNIEXPORT void JNICALL Java_beginend_BeginEnd_stop(JNIEnv* env, jclass cls) {
}
